const $=s=>document.querySelector(s);const {calculateGrid,pickTile,isSupportedImageFile,calculateTileDecodeSide,usageStats}=window.PhotoMosaicEngine;const {createGenerationController,GenerationCancelledError}=window.PhotoMosaicGeneration;const generation=createGenerationController();const st={target:null,tiles:[],targetUrl:null,tileUrls:[]};
const e={target:$('#target'),tiles:$('#tiles'),targetBox:$('#targetBox'),targetPreview:$('#targetPreview'),changeTarget:$('#changeTarget'),count:$('#count'),clear:$('#clear'),strip:$('#strip'),cols:$('#cols'),colsOut:$('#colsOut'),blend:$('#blend'),blendOut:$('#blendOut'),resolution:$('#resolution'),avoid:$('#avoid'),diversity:$('#diversity'),generate:$('#generate'),message:$('#message'),progress:$('#progress'),bar:$('#bar'),progressText:$('#progressText'),cancel:$('#cancel'),result:$('#result'),canvas:$('#canvas'),download:$('#download'),again:$('#again')};
const busyControls=[e.target,e.tiles,e.changeTarget,e.clear,e.cols,e.blend,e.resolution,e.avoid,e.diversity];e.cols.oninput=()=>e.colsOut.value=e.cols.value;e.blend.oninput=()=>e.blendOut.value=e.blend.value+'%';
e.target.onchange=ev=>{const f=ev.target.files?.[0];ev.target.value='';if(!f)return;if(!isSupportedImageFile(f,40*1024*1024)){e.message.textContent='La foto principal debe ser una imagen de hasta 40 MB.';return}st.target=f;if(st.targetUrl)URL.revokeObjectURL(st.targetUrl);st.targetUrl=URL.createObjectURL(f);e.targetPreview.src=st.targetUrl;e.targetBox.classList.remove('hidden');validate()};e.changeTarget.onclick=()=>e.target.click();
e.tiles.onchange=()=>{const known=new Set(st.tiles.map(f=>f.name+'|'+f.size+'|'+f.lastModified));let rejected=0;for(const f of e.tiles.files){const k=f.name+'|'+f.size+'|'+f.lastModified;if(!isSupportedImageFile(f,25*1024*1024)||st.tiles.length>=300){rejected++;continue}if(!known.has(k)){st.tiles.push(f);known.add(k)}}e.tiles.value='';renderTiles();if(rejected)e.message.textContent=rejected+' archivo(s) omitidos por formato, tamaño o límite de 300 fotos.'};e.clear.onclick=()=>{st.tiles=[];renderTiles()};
function renderTiles(){e.count.textContent=st.tiles.length+' fotos seleccionadas';e.clear.classList.toggle('hidden',!st.tiles.length);st.tileUrls.forEach(URL.revokeObjectURL);st.tileUrls=[];e.strip.innerHTML='';st.tiles.slice(0,80).forEach(f=>{const i=new Image,u=URL.createObjectURL(f);st.tileUrls.push(u);i.src=u;e.strip.append(i)});validate()}
function validate(){const ok=st.target&&st.tiles.length>=10;e.generate.disabled=!ok||generation.isRunning();e.message.textContent=!st.target&&st.tiles.length<10?'Añade una foto principal y al menos 10 fotos.':!st.target?'Falta la foto principal.':st.tiles.length<10?'Añade '+(10-st.tiles.length)+' fotos más.':'Todo listo para crear el mosaico.'}
function setBusy(busy){busyControls.forEach(control=>control.disabled=busy);e.generate.disabled=busy||!st.target||st.tiles.length<10;e.cancel.disabled=false;e.cancel.classList.toggle('hidden',!busy);e.progress.setAttribute('aria-busy',String(busy))}
function load(f,maxSide=1024){return new Promise((res,rej)=>{const i=new Image,u=URL.createObjectURL(f);i.onload=()=>{URL.revokeObjectURL(u);const scale=Math.min(1,maxSide/Math.max(i.naturalWidth,i.naturalHeight));if(scale===1)return res(i);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(i.naturalWidth*scale));c.height=Math.max(1,Math.round(i.naturalHeight*scale));c.getContext('2d').drawImage(i,0,0,c.width,c.height);res(c)};i.onerror=()=>{URL.revokeObjectURL(u);rej(Error('No se pudo leer '+f.name))};i.src=u})}
function avg(img){const c=document.createElement('canvas');c.width=c.height=24;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,24,24);const d=x.getImageData(0,0,24,24).data;let r=0,g=0,b=0,n=0;for(let j=0;j<d.length;j+=4){if(d[j+3]<20)continue;r+=d[j];g+=d[j+1];b+=d[j+2];n++}return[r/n||128,g/n||128,b/n||128]}
function cover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s;ctx.drawImage(img,(img.width-sw)/2,(img.height-sh)/2,sw,sh,x,y,w,h)}
function prog(p,t){e.bar.style.width=p+'%';e.progressText.textContent=t}const frame=()=>new Promise(r=>requestAnimationFrame(r));
async function prepare(signal,snapshot){const tileSide=calculateTileDecodeSide(snapshot.resolution,snapshot.columns);prog(3,'Leyendo foto principal…');signal.throwIfCancelled();const targetImg=await load(snapshot.target,snapshot.resolution);signal.throwIfCancelled();const tileData=[];for(let i=0;i<snapshot.tiles.length;i++){signal.throwIfCancelled();try{const img=await load(snapshot.tiles[i],tileSide);signal.throwIfCancelled();tileData.push({img,color:avg(img),index:i})}catch(err){if(err instanceof GenerationCancelledError)throw err}if(i%3===0){prog(5+i/snapshot.tiles.length*25,'Analizando '+(i+1)+' de '+snapshot.tiles.length+' fotos…');await frame()}}if(tileData.length<10)throw Error('Se necesitan al menos 10 imágenes válidas. Prueba con JPG, PNG, WebP o HEIC compatible.');return{targetImg,tileData}}
async function create(){const signal=generation.start(),snapshot={target:st.target,tiles:[...st.tiles],resolution:+e.resolution.value,columns:+e.cols.value,blend:+e.blend.value/100,avoid:e.avoid.checked,diversity:+e.diversity.value};setBusy(true);e.progress.classList.remove('hidden');e.result.classList.add('hidden');prog(0,'Preparando…');try{const {targetImg,tileData}=await prepare(signal,snapshot);signal.throwIfCancelled();const grid=calculateGrid(targetImg.width,targetImg.height,snapshot.resolution,snapshot.columns),W=grid.width,H=grid.height,cols=grid.columns,tw=grid.tileWidth,rows=grid.rows,th=grid.tileHeight;const sc=document.createElement('canvas');sc.width=cols;sc.height=rows;const sx=sc.getContext('2d',{willReadFrequently:true});sx.drawImage(targetImg,0,0,cols,rows);const data=sx.getImageData(0,0,cols,rows).data;e.canvas.width=W;e.canvas.height=H;const ctx=e.canvas.getContext('2d'),history=[],usage=new Map();for(let r=0;r<rows;r++){signal.throwIfCancelled();const row=[];for(let c=0;c<cols;c++){const k=(r*cols+c)*4,color=[data[k],data[k+1],data[k+2]],recent=[];if(c)recent.push(row[c-1]);if(r)recent.push(history[r-1][c]);if(r&&c)recent.push(history[r-1][c-1]);const tile=pickTile(color,tileData,recent,snapshot.avoid,usage,snapshot.diversity);usage.set(tile.index,(usage.get(tile.index)||0)+1);const x=Math.round(c*tw),y=Math.round(r*th),nx=Math.round((c+1)*tw),ny=Math.round((r+1)*th);cover(ctx,tile.img,x,y,nx-x,ny-y);row.push(tile.index)}history.push(row);if(r%2===0){prog(32+(r+1)/rows*58,'Construyendo fila '+(r+1)+' de '+rows);await frame()}}signal.throwIfCancelled();if(snapshot.blend){ctx.save();ctx.globalAlpha=snapshot.blend;ctx.drawImage(targetImg,0,0,W,H);ctx.restore()}const stats=usageStats(usage,rows*cols);prog(100,'Mosaico terminado · '+stats.unique+' de '+tileData.length+' fotos usadas');e.result.classList.remove('hidden');e.result.scrollIntoView({behavior:'smooth'})}catch(err){if(err instanceof GenerationCancelledError){prog(0,'Creación cancelada. Tus fotos siguen seleccionadas.');e.message.textContent='Creación cancelada. Puedes cambiar los ajustes e intentarlo de nuevo.'}else alert(err.message||'No se pudo crear el mosaico. Prueba con imágenes JPG, PNG o WebP.')}finally{if(generation.finish(signal)){setBusy(false);validate()}}}
async function exportResult(){e.download.disabled=true;try{const blob=await new Promise((res,rej)=>e.canvas.toBlob(b=>b?res(b):rej(Error('No se pudo exportar la imagen')),'image/jpeg',.94)),name='photomosaic-'+new Date().toISOString().slice(0,10)+'.jpg',file=new File([blob],name,{type:'image/jpeg'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'PhotoMosaic'})}else{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}}catch(err){if(err.name!=='AbortError')alert(err.message||'No se pudo guardar la imagen')}finally{e.download.disabled=false}}
e.generate.onclick=create;e.cancel.onclick=()=>{generation.cancel('Cancelada por el usuario');e.cancel.disabled=true;prog(parseFloat(e.bar.style.width)||0,'Cancelando…')};e.download.onclick=exportResult;e.again.onclick=()=>{e.result.classList.add('hidden');scrollTo({top:0,behavior:'smooth'})};addEventListener('pagehide',()=>generation.cancel('La página se cerró'));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));validate();
