import assert from 'node:assert/strict';
await import('../generation-controller.js');
const { createGenerationController, GenerationCancelledError } = globalThis.PhotoMosaicGeneration;
const controller = createGenerationController();
const first = controller.start();
assert.equal(controller.isRunning(), true);
assert.equal(controller.isCurrent(first), true);
first.throwIfCancelled();
const second = controller.start();
assert.equal(first.cancelled, true);
assert.throws(() => first.throwIfCancelled(), GenerationCancelledError);
assert.equal(controller.finish(first), false);
assert.equal(controller.isCurrent(second), true);
controller.cancel('Prueba');
assert.equal(second.cancelled, true);
assert.throws(() => second.throwIfCancelled(), /Prueba/);
assert.equal(controller.finish(second), true);
assert.equal(controller.isRunning(), false);
const third = controller.start();
assert.equal(controller.finish(third), true);
assert.equal(controller.isRunning(), false);
console.log('Generation controller tests passed');
