const { test, expect } = require('@playwright/test');

test('launcher exposes two independent creation modes', async ({ page }) => {const errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await expect(page.getByRole('link',{name:/Abrir mosaico fotográfico/i})).toBeVisible();await expect(page.getByRole('link',{name:/Abrir forma para pared/i})).toBeVisible();expect(errors).toEqual([]);});

test('classic mosaic shows only the classic workflow', async ({ page }) => {const errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto('http://127.0.0.1:4173/studio.html?mode=rectangle',{waitUntil:'domcontentloaded'});await expect(page.locator('#targetSection')).toBeVisible();await expect(page.locator('#mosaicOnlyControls')).toBeVisible();await expect(page.locator('#shapeControls')).toBeHidden();await expect(page.locator('#modeChooser')).toBeHidden();expect(await page.locator('#mosaicMode').inputValue()).toBe('rectangle');expect(errors).toEqual([]);});

test('wall shape hides mosaic-only controls and activates physical planning', async ({ page }) => {const errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto('http://127.0.0.1:4173/studio.html?mode=shape',{waitUntil:'domcontentloaded'});await expect(page.locator('#targetSection')).toBeHidden();await expect(page.locator('#mosaicOnlyControls')).toBeHidden();await expect(page.locator('#shapeControls')).toBeVisible();await expect(page.locator('#modeChooser')).toBeHidden();expect(await page.locator('#mosaicMode').inputValue()).toBe('shape');await expect(page.locator('#photoWidth')).toBeVisible();await expect(page.locator('#photoHeight')).toBeVisible();await expect(page.locator('#photoGap')).toBeVisible();await page.waitForSelector('#wallPreviewSection');await expect(page.locator('#wallPreviewSection')).toBeVisible();await expect(page.locator('#wallPhoto')).toHaveAttribute('accept','image/*');await expect(page.locator('#wallPreviewCanvas')).toBeVisible();const engine=await page.evaluate(()=>({preview:typeof PhotoMosaicWallPreview?.placement,fit:typeof PhotoMosaicWallFit?.assess}));expect(engine.preview).toBe('function');expect(engine.fit).toBe('function');expect(errors).toEqual([]);});

test('generated result freezes source controls until creating another design', async ({ page }) => {const errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto('http://127.0.0.1:4173/studio.html?mode=shape',{waitUntil:'domcontentloaded'});await expect(page.locator('#photoWidth')).toBeEnabled();await page.locator('#result').evaluate(el=>el.classList.remove('hidden'));await expect(page.locator('.result-integrity-note')).toBeVisible();await expect(page.locator('#photoWidth')).toBeDisabled();await expect(page.locator('#photoHeight')).toBeDisabled();await page.locator('#again').click();await expect(page.locator('#result')).toBeHidden();await expect(page.locator('#photoWidth')).toBeEnabled();await expect(page.locator('#photoHeight')).toBeEnabled();expect(errors).toEqual([]);});
